# Generated by Django 5.0.4 on 2025-06-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, default="I'm using Musimatch!", max_length=200),
        ),
    ]
