# Generated by Django 5.0.4 on 2024-04-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=25)),
                ('song', models.CharField(max_length=50)),
                ('timeperiod', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
