# Generated by Django 5.0.4 on 2024-04-11 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='timeperiod',
            new_name='time_period',
        ),
    ]
